### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by scotticles** [bywatersolutions/koha-plugin-opac-theme-childrens#5]
I've installed the plugin, I went to configure it and im not sure how to actually use this plugin. 
Kids OPAC URL #1:  what do i exactly put here and then how do i access it? 

Thanks.

**Comment by lauraesca** [comment]
Hi Scotticles! If you are still in need of assistance setting up your Kids OPAC plugin please reach out to us at support@bywatersolutions.com
